version: '3'
services:
  spring-app:
    build:
      context: .
      dockerfile: spring-projeto-piloto/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - react-app

  react-app:
    image: node:14
    command: npm start
    working_dir: /app/vite-projeto-piloto
    volumes:
      - .:/app
    ports:
      - "5173:5173"